<a href="https://colab.research.google.com/github/NikhithaAlla/Nikhitha_Data690/blob/main/assignment_05/Assignment_05_Part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Assignment 05

- Name: Nikhitha Alla

- Date: 03/05/22


#Hands on!

In [1]:
import sys
import numpy as np
import warnings

#Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])


In [4]:
b = np.array([0, .5, 1, 1.5, 2])


In [5]:
a[0], a[1]

(1, 2)

In [6]:
a[0:]

array([1, 2, 3, 4])

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]


array([2, 3])

In [9]:
a[::2]


array([1, 3])

In [10]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [11]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [12]:
b[[0, 2, -1]]

array([0., 1., 2.])

#Array Types

In [13]:
a

array([1, 2, 3, 4])

In [14]:
a.dtype

dtype('int64')

In [15]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
b.dtype

dtype('float64')

In [17]:
np.array([1, 2, 3, 4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([1., 2., 3., 4.])

In [18]:
np.array([1, 2, 3, 4], dtype=np.int8)


array([1, 2, 3, 4], dtype=int8)

In [19]:
c = np.array(['a', 'b', 'c'])

In [20]:
c.dtype

dtype('<U1')

In [21]:
d = np.array([{'a': 1}, sys])


In [22]:
d.dtype

dtype('O')

#Dimesnsions and shapes

In [23]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [24]:
A.shape

(2, 3)

In [25]:
A.ndim

2

In [26]:
A.size

6

In [27]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [28]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
B.shape


(2, 2, 3)

In [30]:
B.ndim

3

In [31]:
B.size

12

In [32]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  import sys


In [33]:
C.dtype

dtype('O')

In [34]:
C.dtype

dtype('O')

In [35]:
C.size

2

In [36]:
type(C[0])

list

#Indexing and Slicing of Matrices

In [37]:
# Square matrix
A = np.array([
#.   0. 1. 2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [38]:
A[1]

array([4, 5, 6])

In [39]:
A[1][0]

4

In [40]:
# A[d1, d2, d3, d4]

In [41]:
A[1, 0]

4

In [42]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
A[:, :2]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [44]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2, 2:]

array([[3],
       [6]])

In [46]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[1] = np.array([10, 10, 10])

In [48]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [49]:
A[2] = 99

In [50]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

#Summary statistics

In [51]:
a = np.array([1, 2, 3, 4])

In [52]:
a.sum()

10

In [53]:
a.mean()

2.5

In [54]:
a.std()

1.118033988749895

In [55]:
a.var()

1.25

In [56]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


In [57]:
A.sum()

45

In [58]:
A.mean()

5.0

In [59]:
A.std()

2.581988897471611

In [60]:
A.sum(axis=0)

array([12, 15, 18])

In [61]:
A.sum(axis=1)

array([ 6, 15, 24])

In [62]:
A.mean(axis=0)

array([4., 5., 6.])

In [63]:
A.mean(axis=1)

array([2., 5., 8.])

In [64]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [65]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

#Broadcasting and Vectorized operations

In [66]:
a = np.arange(4)

In [67]:
a

array([0, 1, 2, 3])

In [68]:
a + 10

array([10, 11, 12, 13])

In [69]:
a * 10

array([ 0, 10, 20, 30])

In [70]:
a

array([0, 1, 2, 3])

In [71]:
a += 100

In [72]:
a

array([100, 101, 102, 103])

In [73]:
l = [0, 1, 2, 3]

In [74]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [75]:
a = np.arange(4)


In [76]:
a

array([0, 1, 2, 3])

In [77]:
b = np.array([10, 10, 10, 10])

In [78]:
b

array([10, 10, 10, 10])

In [79]:
a + b

array([10, 11, 12, 13])

In [80]:
a * b

array([ 0, 10, 20, 30])

#Boolean arrays

In [81]:
a = np.arange(4)

In [82]:
a

array([0, 1, 2, 3])

In [83]:
a[0], a[-1]


(0, 3)

In [84]:
a[[0, -1]]


array([0, 3])

In [85]:
a[[True, False, False, True]]

array([0, 3])

In [86]:
a

array([0, 1, 2, 3])

In [87]:
a >= 2

array([False, False,  True,  True])

In [88]:
a[a >= 2]

array([2, 3])

In [89]:
a.mean()

1.5

In [90]:
a[a > a.mean()]

array([2, 3])

In [91]:
a[~(a > a.mean())]


array([0, 1])

In [92]:
a[(a == 0) | (a == 1)]


array([0, 1])

In [93]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [94]:
A = np.random.randint(100, size=(3, 3))

In [95]:
A

array([[41, 30, 31],
       [55, 68, 49],
       [62, 13, 22]])

In [96]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([41, 31, 68, 62, 22])

In [97]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [98]:
A[A > 30]


array([41, 31, 55, 68, 49, 62])

#Linear Algebra

In [99]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [100]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [101]:
A.dot(B)


array([[20, 14],
       [56, 41],
       [92, 68]])

In [102]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [103]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [104]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

#Size of objects in Memory

 ## Int, floats

In [106]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [107]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [108]:
# Numpy size is much smaller
np.dtype(int).itemsize

8

In [109]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [110]:
np.dtype(float).itemsize

8

# Lists are even larger

In [111]:
# A one-element list
sys.getsizeof([1])

80

In [112]:
# An array of one element in numpy
np.array([1]).nbytes

8

#And performance is also important

In [113]:
l = list(range(100000))

In [114]:
a = np.arange(100000)

In [115]:
%time np.sum(a ** 2)

CPU times: user 1.39 ms, sys: 910 µs, total: 2.3 ms
Wall time: 5.52 ms


333328333350000

In [116]:
%time sum([x ** 2 for x in l])

CPU times: user 49.6 ms, sys: 3.76 ms, total: 53.4 ms
Wall time: 63.8 ms


333328333350000

#Useful Numpy functions

##random

In [117]:
np.random.random(size=2)

array([0.14177671, 0.5167462 ])

In [118]:
np.random.normal(size=2)


array([-0.31231223, -0.06202234])

In [119]:
np.random.rand(2, 4)

array([[0.51571625, 0.69174808, 0.9536154 , 0.61187336],
       [0.84859728, 0.42769576, 0.92312308, 0.29946839]])

#arrange

In [120]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [122]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#reshape

In [123]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [124]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#Linespace

In [125]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [126]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [127]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

# zeros, ones, empty

In [128]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [129]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
np.zeros((3, 3), dtype=np.int)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [131]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [132]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [133]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [134]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#Identity and eye

In [135]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [136]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [137]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [138]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [139]:
np.eye(8, 4, k=3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [140]:
"Hello World"[6]


'W'